title: Scionx Docs
description: Official documentation for the Scionx platform

theme: just-the-docs

url: https://github.com/scionx-io/doc

aux_links:
  Template Repository: https://github.com/scionx-io/doc

color_scheme: dark
logo: "/assets/images/logo.png"
favicon_ico: "/assets/images/favicon.ico"



plugins:
  - jekyll-default-layout
  - jekyll-email-protect